import Link from "next/link";
import { FAQAccordion, HeroCarousel, Testimonials } from "@/components/home-interactive";
import { ProductCard, SectionHead } from "@/components/ui";
import { QuoteForm } from "@/components/quote-form";
import { products, trustBadges } from "@/lib/data";

export default function Home() {
  return <>
    <HeroCarousel />
    <section className="border-y border-gold/20 bg-[#f1eadc]"><div className="container-site grid gap-4 py-5 text-center text-xs font-bold uppercase tracking-[.12em] text-leaf md:grid-cols-3"><span>✓ Product-specific quality checks</span><span>✓ Ethical and responsible sourcing</span><span>✓ Responsive service and logistics</span></div></section>
    <section className="bg-[#f8f5ee] py-24 md:py-32"><div className="container-site grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHead eyebrow="About IGLOBALAGREECARE" title="Indian products. Global possibilities."/><p className="mt-7 text-sm leading-7 text-ink/65">IGLOBALAGREECARE connects commercial buyers with a focused range of Indian agricultural inputs, food ingredients and industrial packaging products. We bring each enquiry into one clear sourcing conversation—from initial specification through packing and dispatch planning.</p><p className="mt-4 text-sm leading-7 text-ink/65">Our approach combines responsive service with practical quality checks and responsible supplier relationships. Whether you require natural farm products, processed ingredients or load-securing materials, we work to make procurement straightforward.</p><Link href="/about" className="mt-7 inline-block text-xs font-bold uppercase tracking-wider text-gold">Learn more about us →</Link></div><div className="grid gap-4 sm:grid-cols-2">{trustBadges.map(([number, title, copy]) => <article className="rounded-2xl bg-white p-6" key={title}><b className="font-display text-2xl text-gold">{number}</b><h3 className="mt-4 text-2xl font-medium text-leaf">{title}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{copy}</p></article>)}</div></div></section>
    <section className="bg-white py-24 md:py-32"><div className="container-site"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHead eyebrow="Our range" title="Products selected for real business needs." copy="Explore our complete export-oriented range across agriculture, natural ingredients and packaging."/><Link href="/contact" className="text-xs font-bold uppercase tracking-wider text-gold">Inquire about other products →</Link></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <ProductCard product={product} key={product.slug}/>)}</div></div></section>
    <section className="bg-[#f1ece2] py-24 md:py-32"><div className="container-site grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHead eyebrow="Common questions" title="Clear answers before you order."/><FAQAccordion/></div></section>
    <section className="bg-forest py-24 text-white md:py-32"><div className="container-site grid items-start gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Get a quote</p><h2 className="section-title">Tell us what<br/><em className="text-[#e9bb84]">you need.</em></h2><p className="mt-6 text-sm leading-7 text-white/60">Share the product, approximate volume and destination. Our team will respond with the next practical steps.</p></div><QuoteForm compact/></div></section>
    <section className="bg-[#f8f5ee] py-24"><div className="container-site"><SectionHead eyebrow="Certified quality" title="Documentation aligned with each order." copy="Compliance documents vary by product and destination. We confirm applicable certificates and shipment records during quotation."/><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{["APEDA","IEC","ISO 22000","FSSAI","Organic / NPOP","Phytosanitary"].map((name) => <div key={name} className="grid aspect-square place-items-center rounded-full border border-gold/35 bg-white p-4 text-center font-display text-lg text-leaf">{name}</div>)}</div><Link href="/certificates" className="mt-8 inline-block text-xs font-bold uppercase tracking-wider text-gold">View certificates & quality →</Link>{/* [CUSTOMIZE: replace with certifications the business actually holds] */}</div></section>
    <section className="bg-[#f1ece2] py-24"><div className="container-site grid gap-12 lg:grid-cols-2"><div><SectionHead eyebrow="Client perspective" title="Built around responsive trade."/><div className="mt-8"><Testimonials/></div></div><div><SectionHead eyebrow="Global reach" title="Prepared for international enquiries."/><div className="mt-8 rounded-3xl bg-white p-8"><b className="font-display text-5xl text-leaf">X+ countries</b><p className="mt-3 text-sm text-ink/55">Export markets to be confirmed.</p><div className="mt-7 flex flex-wrap gap-2">{["Market 01","Market 02","Market 03","Market 04"].map((market) => <span key={market} className="rounded-full bg-[#f8f5ee] px-4 py-2 text-xs text-ink/55">{market}</span>)}</div></div>{/* [CUSTOMIZE: update with actual export markets] */}</div></div></section>
    <section className="bg-gold py-12 text-white"><div className="container-site flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><h2 className="text-4xl font-medium">Looking to import in bulk? Let&apos;s talk.</h2><Link href="/contact" className="rounded-full bg-forest px-7 py-3 text-xs font-bold uppercase tracking-wider">Get a quote</Link></div></section>
  </>;
}
