"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Logo } from "./logo";
import { contact, products } from "@/lib/data";

const nav = [["Home", "/"], ["About", "/about"], ["Products", "/products"], ["Certificates", "/certificates"], ["Contact", "/contact"]];

export function Header() {
  const [open, setOpen] = useState(false); const [overHero, setOverHero] = useState(true);
  useEffect(() => { const update = () => setOverHero(window.scrollY < 80); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  const clear = overHero && !open;
  return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${clear ? "bg-transparent text-white" : "border-b border-black/5 bg-[#f8f5ee]/95 text-ink shadow-sm backdrop-blur-xl"}`}><div className="container-site flex h-[72px] items-center justify-between md:h-[78px]"><Logo light={clear}/><nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">{nav.map(([name, href]) => name === "Products" ? <div className="group relative" key={href}><Link className={`text-sm font-semibold tracking-wide transition hover:text-gold ${clear ? "text-white/90" : "text-ink/65"}`} href={href}>Products ↓</Link><div className="invisible absolute left-1/2 top-full w-[540px] -translate-x-1/2 pt-6 opacity-0 transition group-hover:visible group-hover:opacity-100"><div className="grid grid-cols-2 gap-1 rounded-2xl border border-forest/10 bg-[#f8f5ee] p-5 text-ink shadow-2xl">{products.map((product) => <Link className="rounded-lg px-3 py-2 text-xs font-semibold text-ink/65 hover:bg-white hover:text-gold" href={`/products/${product.slug}`} key={product.slug}>{product.name}</Link>)}</div></div></div> : <Link className={`text-sm font-semibold tracking-wide transition hover:text-gold ${clear ? "text-white/90" : "text-ink/65"}`} href={href} key={href}>{name}</Link>)}</nav><div className="flex items-center gap-3"><Link href="/contact" className={`hidden rounded-full px-5 py-2.5 text-[11px] font-bold uppercase tracking-[.12em] sm:block ${clear ? "bg-white text-forest" : "bg-forest text-white"}`}>Get in touch</Link><button onClick={() => setOpen(!open)} className={`grid h-10 w-10 place-items-center rounded-full border text-lg lg:hidden ${clear ? "border-white/35 text-white" : "border-forest/15 text-ink"}`} aria-label="Toggle navigation" aria-expanded={open}>{open ? "×" : "☰"}</button></div></div>{open && <nav className="max-h-[calc(100vh-72px)] overflow-y-auto border-t border-forest/10 bg-[#f8f5ee] px-5 py-4 text-ink lg:hidden">{nav.map(([name, href]) => <div key={href}><Link onClick={() => setOpen(false)} className="flex items-center justify-between border-b border-forest/8 py-3.5 text-sm font-semibold" href={href}>{name}<span className="text-gold">→</span></Link>{name === "Products" && <div className="grid grid-cols-2 gap-1 border-b border-forest/8 py-3">{products.map((product) => <Link onClick={() => setOpen(false)} className="rounded-lg px-2 py-2 text-[11px] text-ink/60" href={`/products/${product.slug}`} key={product.slug}>{product.name}</Link>)}</div>}</div>)}</nav>}</header>;
}

export function Footer() { return <footer className="bg-[#0d2516] text-white"><div className="container-site grid gap-12 py-16 md:grid-cols-2 lg:grid-cols-[1.2fr_.65fr_1fr_1fr]"><div><Logo light/><p className="mt-6 max-w-sm text-xs leading-6 text-white/50">Indian agricultural, food-ingredient and packaging products prepared for domestic and international buyers.</p></div><div><h3 className="text-sm font-semibold text-[#e5b881]">Company</h3><div className="mt-5 grid gap-2.5 text-xs text-white/45"><Link href="/about">About</Link><Link href="/certificates">Certificates</Link><Link href="/contact">Contact</Link><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-conditions">Terms & Conditions</Link></div></div><div><h3 className="text-sm font-semibold text-[#e5b881]">Products</h3><div className="mt-5 grid grid-cols-2 gap-2.5 text-xs text-white/45">{products.map((product) => <Link className="hover:text-white" href={`/products/${product.slug}`} key={product.slug}>{product.name}</Link>)}</div></div><div><h3 className="text-sm font-semibold text-[#e5b881]">Reach us</h3><div className="mt-5 space-y-3 text-xs leading-6 text-white/45"><p>{contact.address}</p><a className="block hover:text-white" href={`tel:${contact.phone}`}>{contact.phone}</a><a className="hover:text-white" href={`mailto:${contact.email}`}>{contact.email}</a></div></div></div><div className="border-t border-white/8"><div className="container-site flex flex-col gap-2 py-5 text-[9px] uppercase tracking-[.14em] text-white/30 sm:flex-row sm:justify-between"><span>© 2026 IGLOBALAGREECARE</span><span>Quality sourcing · Responsible trade · Reliable delivery</span></div></div></footer>; }
export function WhatsApp() { return <a href={`https://wa.me/${contact.whatsapp}`} target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp" className="fixed bottom-4 right-4 z-40 grid h-13 w-13 place-items-center rounded-full border-4 border-white bg-[#25D366] text-xs font-bold text-white shadow-xl transition hover:scale-105 sm:bottom-6 sm:right-6">WA</a>; }
